language: ruby
node_js: stable
before_script:
  - gem install jekyll
  - bundle install
script:
  - bundle exec jekyll build
deploy:
  provider: pages
  local_dir: _site
  repo: rhatyang/hexo-demo
  skip_cleanup: true
  github_token: $blog
  on:
    branch: master
  target_branch: gh-pages
