language: node_js
node_js: stable
install:
  - npm install
before_script:
  - npm install -g gulp-cli
script:
  - npm start
  - gulp build
deploy:
  provider: pages
  local_dir: public
  repo: rhatyang/blog
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  target_branch: gh-pages
