language: node_js
node_js: stable
install:
  - npm install
before_script:
  - chmod 777 -R script
script: script/build.sh
deploy:
  provider: pages
  local_dir: public
  repo: rhatyang/blog
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  target_branch: gh-pages
