language: node_js
node_js: stable
before_script:
  - npm install hexo-cli -g
script:
  - hexo generate
deploy:
  provider: pages
  local_dir: public
  repo: rhatyang/hexo-demo
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  target_branch: gh-pages
