language: node_js
node_js: stable
install:
  - npm install
before_script:
  - npm install -g gulp-cli
script: 
  - npm start
  - gulp build
  - sudo apt-get install lftp -y
  - lftp -c "open -u $FTP_USER,$FTP_PASSWD $FTP_ADDRESS; set ssl:verify-certificate no; mirror -R ./public/ /"
