title: 樊志阳的个人博客
index_title: 樊志阳的个人博客 | Life is too short. Don't do what you don't like to do
author: 樊志阳
email: fanzhiyang2001@gmail.com
description: 见过婴儿心花怒放之笑，只觉得成长格外悲凉。
url: https://fanzhiyang.com
permalink: /blog/:title/
markdown: kramdown
excerpt_separator: <!-- more -->
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
feed:
  path: /blog/atom.xml
paginate: 5
paginate_path: "/pages:num/"