
title: 樊志阳的BLOG
author: 樊志阳
url: https://fanzhiyang.com
permalink: blog/:title/
source_dir: source
public_dir: public
archive_dir: blog
category_dir: blog
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
index_generator:
  path: ''
  per_page: 5
  order_by: -date
archive_generator:
  per_page: 5
default_category: 杂文
category_map:
  网络技术与安全: network
  使用笔记: use
  学习笔记: learn
  历史爱好者: history
  晃眼一生: lifetime
  Unix/Linux: linux
  JavaScript: javascript
  杂文: other
  观后感: review
date_format: YYYY年M月D日
time_format: HH:mm:ss
per_page: 0
pagination_dir: page
theme: zy
plugin:
  - hexo-generator-feed
  - hexo-generator-sitemap
  - hexo-generator-baidu-sitemap
feed:
  type: atom
  path: blog/atom.xml
  limit: 20
  content_limit: 140
  content_limit_delim: ' '
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml
