title: 樊志阳的个人博客
index_title: 樊志阳的个人博客 | Life is too short. Don't do what you don't like to do
author: 樊志阳
email: fanzhiyang2001@gmail.com
author-bio: Valar Morghulis~~
url: https://fanzhiyang.com
permalink: /blog/:title/
markdown: kramdown
excerpt_separator: <!-- more -->
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
feed:
  path: /blog/atom.xml
paginate: 5
paginate_path: "/page/:num/"
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - package.json
  - gulpfile.js
  - node_modules
  - _site
